name: Bug Report
description: Report a bug
labels: [ "bug" ]
body:
  - type: checkboxes
    id: platforms
    attributes:
      label: Affected Platforms
      description: Which platforms did you encounter the bug on? Please select all that apply.
      options:
        - id: android
          label: Android
        - id: ios
          label: iOS
        - id: web
          label: Web
        - id: windows
          label: Windows
        - id: macos
          label: macOS
        - id: linux
          label: Linux
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System Version
      description: What Operating System version did you use? (e.g. Windows 10, macOS 12.3, Android 11, iOS 15.4).
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version of flutter-maplibre
      description: What version of maplibre are you using? (e.g. `0.0.1` or `main branch` + commit hash)
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Bug Description
      description: Please give a quick description about the bug want to report.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please list the steps required to reproduce the problem one by one.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: Please describe what is expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: Please describe what is actually happening. You can add logs, screenshots or videos.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code Sample
      description: |
        Please paste the code of how you use the package below between the lines with the backticks.
        
        Note: Please do not upload screenshots of code. Instead, use code blocks
        or share a link to a GitHub Gist or Repository.
      value: |
        ```dart
        // Paste your code here
        ```
    validations:
      required: true
